[project]
name = "GazeLabPy"
version = "0.1.0"
description = "Add a short description here"
authors = ["chanyca <chanyca@caltech.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64","win-64"]

[tasks]

[dependencies]
- python = "3.9"
- pip = "24.0"
- psychopy
- pupil-labs-realtime-api
- real-time-screen-gaze
- matplotlib

